//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reparo.Shared.Components.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reparo.Shared.Components.Resource.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name already exists. Enter a unique file name..
        /// </summary>
        internal static string AlreadyUploadedMsg {
            get {
                return ResourceManager.GetString("AlreadyUploadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API call to {0} failed. .
        /// </summary>
        internal static string ApiFailedMessage {
            get {
                return ResourceManager.GetString("ApiFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment &apos;{0}&apos; added successfully..
        /// </summary>
        internal static string AttachmentAddedSuccess {
            get {
                return ResourceManager.GetString("AttachmentAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit pending attachments. Please wait until the case is saved..
        /// </summary>
        internal static string AttachmentCannotEditPending {
            get {
                return ResourceManager.GetString("AttachmentCannotEditPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment &apos;{0}&apos; deleted successfully..
        /// </summary>
        internal static string AttachmentDeletedSuccess {
            get {
                return ResourceManager.GetString("AttachmentDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a document type..
        /// </summary>
        internal static string AttachmentDocTypeRequired {
            get {
                return ResourceManager.GetString("AttachmentDocTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add attachment: {0}.
        /// </summary>
        internal static string AttachmentFailedToAdd {
            get {
                return ResourceManager.GetString("AttachmentFailedToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attachment: {0}.
        /// </summary>
        internal static string AttachmentFailedToDelete {
            get {
                return ResourceManager.GetString("AttachmentFailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load document types: {0}.
        /// </summary>
        internal static string AttachmentFailedToLoadDocTypes {
            get {
                return ResourceManager.GetString("AttachmentFailedToLoadDocTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the uploaded file: {0}.
        /// </summary>
        internal static string AttachmentFailedToReadFile {
            get {
                return ResourceManager.GetString("AttachmentFailedToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file into memory: {0}.
        /// </summary>
        internal static string AttachmentFailedToReadMemory {
            get {
                return ResourceManager.GetString("AttachmentFailedToReadMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove pending attachment..
        /// </summary>
        internal static string AttachmentFailedToRemovePending {
            get {
                return ResourceManager.GetString("AttachmentFailedToRemovePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stage attachment: {0}.
        /// </summary>
        internal static string AttachmentFailedToStage {
            get {
                return ResourceManager.GetString("AttachmentFailedToStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attachment: {0}.
        /// </summary>
        internal static string AttachmentFailedToUpdate {
            get {
                return ResourceManager.GetString("AttachmentFailedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the uploaded file. Please try uploading the file again..
        /// </summary>
        internal static string AttachmentFileAccessError {
            get {
                return ResourceManager.GetString("AttachmentFileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pending attachment reference..
        /// </summary>
        internal static string AttachmentInvalidPendingReference {
            get {
                return ResourceManager.GetString("AttachmentInvalidPendingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document selected for update..
        /// </summary>
        internal static string AttachmentNoDocumentForUpdate {
            get {
                return ResourceManager.GetString("AttachmentNoDocumentForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document selected for deletion..
        /// </summary>
        internal static string AttachmentNoDocumentSelected {
            get {
                return ResourceManager.GetString("AttachmentNoDocumentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document types found for UM and Claim..
        /// </summary>
        internal static string AttachmentNoDocumentTypesFound {
            get {
                return ResourceManager.GetString("AttachmentNoDocumentTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending attachment &apos;{0}&apos; removed successfully..
        /// </summary>
        internal static string AttachmentPendingRemovedSuccess {
            get {
                return ResourceManager.GetString("AttachmentPendingRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attachment is pending upload. It will be uploaded when you save the case..
        /// </summary>
        internal static string AttachmentPendingUploadWarning {
            get {
                return ResourceManager.GetString("AttachmentPendingUploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference context is missing. Cannot delete attachment..
        /// </summary>
        internal static string AttachmentReferenceMissing {
            get {
                return ResourceManager.GetString("AttachmentReferenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference context is missing. Cannot update attachment..
        /// </summary>
        internal static string AttachmentReferenceMissingUpdate {
            get {
                return ResourceManager.GetString("AttachmentReferenceMissingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment &apos;{0}&apos; will be uploaded when the case is saved..
        /// </summary>
        internal static string AttachmentStagedForUpload {
            get {
                return ResourceManager.GetString("AttachmentStagedForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment updated successfully..
        /// </summary>
        internal static string AttachmentUpdatedSuccess {
            get {
                return ResourceManager.GetString("AttachmentUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a file before adding an attachment..
        /// </summary>
        internal static string AttachmentUploadFileRequired {
            get {
                return ResourceManager.GetString("AttachmentUploadFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is invalid..
        /// </summary>
        internal static string BirthDateValidationMessage {
            get {
                return ResourceManager.GetString("BirthDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim {0} for case {1} was already routed for review..
        /// </summary>
        internal static string ClaimExistsInWorkflow {
            get {
                return ResourceManager.GetString("ClaimExistsInWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim  {0} can&apos;t be routed because it&apos;s not a 1500, UB-04, or Dental claim form type..
        /// </summary>
        internal static string ClaimFormTypeWarningMessage {
            get {
                return ResourceManager.GetString("ClaimFormTypeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim can&apos;t be routed because it&apos;s not the latest claim..
        /// </summary>
        internal static string ClaimIsNotLatestMsg {
            get {
                return ResourceManager.GetString("ClaimIsNotLatestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim is currently locked by {0} and cannot be recalled..
        /// </summary>
        internal static string ClaimLockedBannerMessage {
            get {
                return ResourceManager.GetString("ClaimLockedBannerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim {0} recalled successfully..
        /// </summary>
        internal static string ClaimRecallSuccessMessage {
            get {
                return ResourceManager.GetString("ClaimRecallSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim {0} is attached to the case {1} and is routed by {2} at {3} to the queue {4} which is due at {5}. Case coordinator: {6}..
        /// </summary>
        internal static string ClaimRouteNoteMessage {
            get {
                return ResourceManager.GetString("ClaimRouteNoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim did not qualify for any routing rules..
        /// </summary>
        internal static string ClaimRouteNotQualify {
            get {
                return ResourceManager.GetString("ClaimRouteNotQualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim routed to workflow as per rule &lt;i&gt;{0}&lt;/i&gt; on {1}..
        /// </summary>
        internal static string ClaimRouteSucessMessage {
            get {
                return ResourceManager.GetString("ClaimRouteSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondence (Correspondence ID: {0} ) saved successfully..
        /// </summary>
        internal static string CorrespondenceSuccessMessage {
            get {
                return ResourceManager.GetString("CorrespondenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attachment?.
        /// </summary>
        internal static string DeleteAttachment {
            get {
                return ResourceManager.GetString("DeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attachment?.
        /// </summary>
        internal static string DeleteAttachmentMessage {
            get {
                return ResourceManager.GetString("DeleteAttachmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Types.
        /// </summary>
        internal static string DocumentTypesTitle {
            get {
                return ResourceManager.GetString("DocumentTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note cannot be empty or contain only whitespace..
        /// </summary>
        internal static string EmptyNoteComment {
            get {
                return ResourceManager.GetString("EmptyNoteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating Attachment.
        /// </summary>
        internal static string ErrorCreatingAttachmentTitle {
            get {
                return ResourceManager.GetString("ErrorCreatingAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Attachment.
        /// </summary>
        internal static string ErrorDeletingAttachmentTitle {
            get {
                return ResourceManager.GetString("ErrorDeletingAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the application. Retry the action. If the issue continues, contact the system administrator..
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating Attachment.
        /// </summary>
        internal static string ErrorUpdatingAttachmentTitle {
            get {
                return ResourceManager.GetString("ErrorUpdatingAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Claims.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FailureTitle {
            get {
                return ResourceManager.GetString("FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Access Error.
        /// </summary>
        internal static string FileAccessErrorTitle {
            get {
                return ResourceManager.GetString("FileAccessErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name exceeds the maximum length of 50 characters..
        /// </summary>
        internal static string FileNameCharMsg {
            get {
                return ResourceManager.GetString("FileNameCharMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Read Error.
        /// </summary>
        internal static string FileReadErrorTitle {
            get {
                return ResourceManager.GetString("FileReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim can&apos;t be routed because it&apos;s not finalized..
        /// </summary>
        internal static string FinalizedClaimRoutingWarningMessage {
            get {
                return ResourceManager.GetString("FinalizedClaimRoutingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string MandatoryFieldMessage {
            get {
                return ResourceManager.GetString("MandatoryFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9*][0-9*][0-9*]-[0-9*][0-9*]-[0-9][0-9][0-9][0-9].
        /// </summary>
        internal static string MaskSsnLongFormat {
            get {
                return ResourceManager.GetString("MaskSsnLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string MaskSsnShortFormat {
            get {
                return ResourceManager.GetString("MaskSsnShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000-0000.
        /// </summary>
        internal static string MaskZipLongFormat {
            get {
                return ResourceManager.GetString("MaskZipLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000.
        /// </summary>
        internal static string MaskZipShortFormat {
            get {
                return ResourceManager.GetString("MaskZipShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size cannot exceed 4 MB..
        /// </summary>
        internal static string MaxFileSizeErrorMsg {
            get {
                return ResourceManager.GetString("MaxFileSizeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient access group rights to view this member. This member has enrollment with Access groups .
        /// </summary>
        internal static string MemberInvalidAccessMsg {
            get {
                return ResourceManager.GetString("MemberInvalidAccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 3 files can be attached..
        /// </summary>
        internal static string MoreThanFilesErrorMsg {
            get {
                return ResourceManager.GetString("MoreThanFilesErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 3 files can be attached.\n&quot; + Failed to Upload.
        /// </summary>
        internal static string MoreThanFilesFailedErrorMsg {
            get {
                return ResourceManager.GetString("MoreThanFilesFailedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain at least two alphanumeric characters..
        /// </summary>
        internal static string NameValidationMessage {
            get {
                return ResourceManager.GetString("NameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found. Modify your search criteria and try again..
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPI is invalid..
        /// </summary>
        internal static string NpiValidationMessage {
            get {
                return ResourceManager.GetString("NpiValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file is required..
        /// </summary>
        internal static string PdfTypeErrorMsg {
            get {
                return ResourceManager.GetString("PdfTypeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Attachment.
        /// </summary>
        internal static string PendingAttachmentTitle {
            get {
                return ResourceManager.GetString("PendingAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid phone number..
        /// </summary>
        internal static string PhoneNumberValidationMessage {
            get {
                return ResourceManager.GetString("PhoneNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} has not been selected, please select a {0} and try again..
        /// </summary>
        internal static string QuickAppErrorMessage {
            get {
                return ResourceManager.GetString("QuickAppErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} before adding the {1} note..
        /// </summary>
        internal static string SaveBeforeAddingNoteMessage {
            get {
                return ResourceManager.GetString("SaveBeforeAddingNoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the case before routing claim..
        /// </summary>
        internal static string SaveBeforeRouteClaim {
            get {
                return ResourceManager.GetString("SaveBeforeRouteClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims matching the Filters.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name cannot contain &lt; or &gt;.
        /// </summary>
        internal static string SpeCharErrorMsg {
            get {
                return ResourceManager.GetString("SpeCharErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech to text on {0} failed with the following error:.
        /// </summary>
        internal static string SpeechToTextError {
            get {
                return ResourceManager.GetString("SpeechToTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To search by SSN, include the member&apos;s name or date of birth..
        /// </summary>
        internal static string SsnSearchValidationMessage {
            get {
                return ResourceManager.GetString("SsnSearchValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the last 4 digits or the entire SSN..
        /// </summary>
        internal static string SSNValidationMessage {
            get {
                return ResourceManager.GetString("SSNValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staged.
        /// </summary>
        internal static string StagedTitle {
            get {
                return ResourceManager.GetString("StagedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the TCS region correctly for this environment. Contact your system administrator for assistance..
        /// </summary>
        internal static string TCSInvalidRegionName {
            get {
                return ResourceManager.GetString("TCSInvalidRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string UDFEmailRequiredMsg {
            get {
                return ResourceManager.GetString("UDFEmailRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  is Required..
        /// </summary>
        internal static string UDFFieldsMessage {
            get {
                return ResourceManager.GetString("UDFFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required.
        /// </summary>
        internal static string UDFSubjectMsg {
            get {
                return ResourceManager.GetString("UDFSubjectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address..
        /// </summary>
        internal static string UDFValidEmailMsg {
            get {
                return ResourceManager.GetString("UDFValidEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t route ITS claims..
        /// </summary>
        internal static string ValidateITSClaimMessage {
            get {
                return ResourceManager.GetString("ValidateITSClaimMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string ValidationErrorTitle {
            get {
                return ResourceManager.GetString("ValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a 5 digit or 9 digit ZIP code..
        /// </summary>
        internal static string ZipCodeValidationMessage {
            get {
                return ResourceManager.GetString("ZipCodeValidationMessage", resourceCulture);
            }
        }
    }
}
