//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reparo.Shared.Models.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reparo.Shared.Models.Resource.ModelResource", typeof(ModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a ID or search for a member/provider..
        /// </summary>
        internal static string DataForm_AtLeastOneProperty_Error {
            get {
                return ResourceManager.GetString("DataForm_AtLeastOneProperty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date in the format MM/DD/YYYY..
        /// </summary>
        internal static string DataForm_DOB_Error {
            get {
                return ResourceManager.GetString("DataForm_DOB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string DataForm_Email_Error {
            get {
                return ResourceManager.GetString("DataForm_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 10 characters..
        /// </summary>
        internal static string DataForm_MinLength_Ten_Error {
            get {
                return ResourceManager.GetString("DataForm_MinLength_Ten_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered keyword must contain at least two alphanumeric characters..
        /// </summary>
        internal static string DataForm_Name_Error {
            get {
                return ResourceManager.GetString("DataForm_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid NPI..
        /// </summary>
        internal static string DataForm_NPI_Error {
            get {
                return ResourceManager.GetString("DataForm_NPI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid phone number..
        /// </summary>
        internal static string DataForm_Phone_Error {
            get {
                return ResourceManager.GetString("DataForm_Phone_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the last 4 digits or the full SSN..
        /// </summary>
        internal static string DataForm_SSN_Error {
            get {
                return ResourceManager.GetString("DataForm_SSN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a 5-digit or 9-digit ZIP code..
        /// </summary>
        internal static string DataForm_ZIP_Error {
            get {
                return ResourceManager.GetString("DataForm_ZIP_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value between 1 and 60..
        /// </summary>
        internal static string ExtendCaseDurationRangeMessage {
            get {
                return ResourceManager.GetString("ExtendCaseDurationRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration is required..
        /// </summary>
        internal static string ExtendDurationMessage {
            get {
                return ResourceManager.GetString("ExtendDurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required..
        /// </summary>
        internal static string ExtendReasonMessage {
            get {
                return ResourceManager.GetString("ExtendReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Case Number must not exceed 15 characters..
        /// </summary>
        internal static string ExternalReview_ExternalCaseId_CharacterLength {
            get {
                return ResourceManager.GetString("ExternalReview_ExternalCaseId_CharacterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Entity is mandatory..
        /// </summary>
        internal static string ExternalReview_ReviewEntityId_Required_Error {
            get {
                return ResourceManager.GetString("ExternalReview_ReviewEntityId_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string MandatoryFieldMessage {
            get {
                return ResourceManager.GetString("MandatoryFieldMessage", resourceCulture);
            }
        }
    }
}
